# Generated by Django 5.2.6 on 2025-10-02 05:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='artworkimage',
            name='artwork',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('digital-art', 'Digital Art'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('jewelry', 'Jewelry'), ('pottery', 'Pottery & Ceramics'), ('textile', 'Textile Art'), ('mixed-media', 'Mixed Media'), ('illustration', 'Illustration'), ('printmaking', 'Printmaking'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='artwork',
            name='artworks_ar_created_809d6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='artwork',
            name='artworks_ar_status_d03118_idx',
        ),
        migrations.RemoveIndex(
            model_name='artwork',
            name='artworks_ar_is_feat_718e04_idx',
        ),
        migrations.RemoveIndex(
            model_name='artwork',
            name='artworks_ar_is_for__948fd7_idx',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='creation_year',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_for_sale',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_framed',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_price_negotiable',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='style',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='artworks.artwork'),
        ),
        migrations.DeleteModel(
            name='ArtworkImage',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
