# Generated by Django 5.2.6 on 2025-09-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'art medium',
                'verbose_name_plural': 'art mediums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself and your art', verbose_name='biography')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('instagram_handle', models.CharField(blank=True, max_length=30, verbose_name='instagram handle')),
                ('twitter_handle', models.CharField(blank=True, max_length=30, verbose_name='twitter handle')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook page')),
                ('art_style', models.CharField(blank=True, max_length=100, verbose_name='art style')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('education', models.TextField(blank=True, verbose_name='education')),
                ('exhibitions', models.TextField(blank=True, help_text='List your exhibitions', verbose_name='exhibitions')),
                ('awards', models.TextField(blank=True, verbose_name='awards and recognitions')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured artist')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified artist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
                ('art_mediums', models.ManyToManyField(blank=True, related_name='artists', to='artists.artmedium')),
            ],
            options={
                'verbose_name': 'artist profile',
                'verbose_name_plural': 'artist profiles',
            },
        ),
    ]
