# Generated by Django 5.2.6 on 2025-10-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='action_type',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('purchase', 'Purchase'), ('search', 'Search'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart'), ('follow_artist', 'Follow Artist')], max_length=20),
        ),
    ]
